### PR TITLE
Fix PHP 8.4 compatibility

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Fix PHP 8.4 compatibility
| Type?             | 
| BC breaks?        | 
| Deprecations?     | 
| Fixed ticket?     | 
| Sponsor company   | 
| How to test?      |

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hello @Hlavtox!

This is your first pull request on [circuit-breaker](https://github.com/PrestaShop/circuit-breaker/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

**Comment by kpodemski** [comment]
cc @jolelievre

**Comment by jolelievre** [comment]
Ok for me, but could be update the CI to add the missing PHP versions while we're at it?

**Review by jolelievre — APPROVED** [review]
Thanks @Hlavtox

**Pull request merged**
